# Generated by Django 5.1.6 on 2025-03-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_product_options_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Pochta rasmi', 'verbose_name_plural': 'Pochta rasmlari'},
        ),
        migrations.AddField(
            model_name='product',
            name='secret_key',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
