# Generated by Django 5.1.6 on 2025-03-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_courier_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'Pochta', 'verbose_name_plural': 'Pochtalar'},
        ),
        migrations.AlterField(
            model_name='product',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
